### ISSUE TITLE
Sometimes the application does not open and has error popup "The extended attributes are inconsistent."

### ISSUE THREAD

**Issue by SlowNStupid** [portapps/borderless-gaming-portable#23]
#### Steps to reproduce this issue

1. Open "borderless-gaming-portable.exe"

#### Expected behaviour

> Opens the app

#### Actual behaviour

> Got popup error window "The extended attributes are inconsistent.", it doesn't generate any log or anything

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 9.5.6-2 win32

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Education 64 bits

**Winver screenshot** : https://why-am-i-he.re/rhmWn3.png

### Screenshots

https://why-am-i-he.re/3auZ3j.png

### Logs

Issue does not generate log file

**Comment by crazy-max** [comment]
Latest release should fix your issue: https://portapps.io/app/borderless-gaming-portable/#download
